//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerInfo_UDTracking
    {
        public int AutoID { get; set; }
        public string BuyerID { get; set; }
        public string BuyerName { get; set; }
        public string BuyerShortName { get; set; }
        public string EntryIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string UDFlag { get; set; }
    }
}
