//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerViewAccess_UDTracking
    {
        public int iAutoID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string ProductID { get; set; }
        public string BuyerID { get; set; }
        public bool AccessFlag { get; set; }
        public string CreatedBy { get; set; }
        public string UserIP { get; set; }
        public System.DateTime EntryTime { get; set; }
        public string UDFlag { get; set; }
    }
}
