//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCheck_UDTracking
    {
        public int AutoID { get; set; }
        public string UserID { get; set; }
        public System.DateTime LogCheck { get; set; }
        public System.DateTime StartsFrom { get; set; }
        public string CreatedBY { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public string EntryIP { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string UDFlag { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    }
}
