//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSummary
    {
        public int iAutoID { get; set; }
        public string UserID { get; set; }
        public string UserIP { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
    }
}
