//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuName
    {
        public int AutoID { get; set; }
        public string MenuID { get; set; }
        public string MenuName1 { get; set; }
        public string MainMenuID { get; set; }
        public Nullable<int> MenuLayer { get; set; }
        public string MenuControl { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CSSClass { get; set; }
        public string FormType { get; set; }
        public int OrderBy { get; set; }
    }
}
