//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails_UDTracking
    {
        public int AutoID { get; set; }
        public Nullable<int> TransactionCount { get; set; }
        public string ProductID { get; set; }
        public string ImageName { get; set; }
        public string UDFlag { get; set; }
    }
}
