//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFieldAccess
    {
        public int iAutoID { get; set; }
        public string BuyerID { get; set; }
        public string CategoryID { get; set; }
        public string FieldID { get; set; }
        public bool Preview { get; set; }
        public string EntryBy { get; set; }
        public string EntryIP { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedIP { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string CRUDFlag { get; set; }
    }
}
