//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFieldName
    {
        public int iAutoID { get; set; }
        public string FieldID { get; set; }
        public string FieldName { get; set; }
        public int SerialNo { get; set; }
    }
}
