//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster_UDTracking
    {
        public int AutoID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string CategoryID { get; set; }
        public string UnitID { get; set; }
        public string EndUser { get; set; }
        public string WashName { get; set; }
        public string ColorName { get; set; }
        public string StyleName { get; set; }
        public string IMG_Product { get; set; }
        public int DesignType { get; set; }
        public string BuyerID { get; set; }
        public string EntryIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string UDFlag { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    }
}
