//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnauthorizedLogInfo
    {
        public int AutoID { get; set; }
        public System.DateTime Date { get; set; }
        public string UserName { get; set; }
        public string EntryIP { get; set; }
    }
}
