//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int AutoID { get; set; }
        public string UserTypeID { get; set; }
        public string UserType1 { get; set; }
        public bool bSave { get; set; }
        public bool bSelect { get; set; }
        public bool bUpdate { get; set; }
        public bool bDelete { get; set; }
        public string EntryIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime EntryDateTime { get; set; }
    }
}
