//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthentication
    {
        public int AutoID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string MenuID { get; set; }
        public bool bShow { get; set; }
        public bool bSave { get; set; }
        public bool bEdit { get; set; }
        public bool bDelete { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    }
}
