//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWiseBuyerAccess
    {
        public int AutoID { get; set; }
        public string UserID { get; set; }
        public string BuyerID { get; set; }
        public bool BuyerAccess { get; set; }
        public string EntryBY { get; set; }
        public string EntryIP { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdateIP { get; set; }
        public System.DateTime EntryDatetime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string UDFlag { get; set; }
    }
}
