//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegister
    {
        public int AutoID { get; set; }
        public string UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Text_Value { get; set; }
        public string UserTypeID { get; set; }
        public string BuyerID { get; set; }
        public string EntryIP { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
